### ISSUE TITLE
Is it available to initial the weight zero?

### ISSUE THREAD

**Issue by luanyunteng** [seungwonpark/RandWireNN#10]
https://github.com/seungwonpark/RandWireNN/blob/6bea89c423fe7c0d46b37f4256953e905986c84c/model/node.py#L13

**Comment by seungwonpark** [comment]
Hi, @luanyunteng 

Of course not. The code you’re looking at actually means that the weights are intialized with 0.5 since the sigmoid is applied to calculate the actual weight.

**Comment by luanyunteng** [comment]
> Hi, @luanyunteng
> 
> Of course not. The code you’re looking at actually means that the weights are intialized with 0.5 since the sigmoid is applied to calculate the actual weight.

Thanks.
