### ISSUE TITLE
in_degree and out_degree

### ISSUE THREAD

**Issue by Jihao-Li** [seungwonpark/RandWireNN#16]
It is illustrated in figure 2 in origin paper that there are 3 input degrees and 4 output degrees in node operation. In a random graph, we can not guarantee the degree of a node. Is it just a analogy?

**Comment by seungwonpark** [comment]
Yes, figure 2 is just an example of nodes in random graph.

**Comment by Jihao-Li** [comment]
Thank you!

**Comment by Jihao-Li** [comment]
In original paper, the author said that input node and output node were excluded. So, there should be 34 nodes in one stage. But I counted the number of nodes in figure 1 in a stage. I found that there are only 33 nodes in one stage. That's to say, the input node was not excluded. Only the output node was excluded. Do I understand correctly?

**Comment by seungwonpark** [comment]
Sorry, I don't know for sure about that. But I don't think the number of nodes won't matter much here since 34 and 33 don't differ much.

**Comment by Jihao-Li** [comment]
How many hours did you use? I saw you said that you used 16 hours on V100. Did you use a single V100? Did you use 1281167 images or 1231167 images?
