### ISSUE TITLE
How long to train an epoch?

### ISSUE THREAD

**Issue by Ernie1** [seungwonpark/RandWireNN#7]
Hi, I am excited to run your code. I run it on 4 TITAN Xp GPU. And yet, each epoch roughly takes 2 hours. Is that normal? What about your time to train an epoch?
Thanks!

**Comment by seungwonpark** [comment]
Hi! Even though I’m not sure how you trained the model using multiple machine, thanks for letting me know.
In my case, it took about 16 hours for 120k steps with batch size 128. I used Tesla V100(16GB). How many steps do you mean by saying 1 epoch?

Seung-won Park
Undergraduate Student
Dept. of Physics and Astronomy & Computer Science Engineering
Seoul National University
yyyyy@snu.ac.kr | http://swpark.me

________________________________

**Comment by Ernie1** [comment]
I just used pytorch ```nn.DataParallel``` to run on multi-GPU and expanded the batch size to 420.
I referred 1 epoch as running through the train dataset. As for you, 1 epoch means 10k steps.

**Comment by seungwonpark** [comment]
I see. Then for my case, it would have took roughly 1.3 hours to run a single epoch.
